Name- Priya Sinha

Roll No.- 18IM30016

Supervisor- Prof. Goutam Sen

FLIGHT SCHEDULING

In [ ]:
import pandas as pd  #Importing data
import numpy as np   #For supporting arrays
import cvxpy as cp   #Interger Linear Programming

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/flight_schedule.csv")
df

Unnamed: 0  ...  Unnamed: 8
0             Requirement (Flight)  ...           8
1              New York to Buffalo  ...           0
2           New York to Cincinnati  ...           0
3              New York to Chicago  ...           1
4               Buffalo to Chicago  ...           0
5            Chicago to Cincinnati  ...           0
6         Cincinnati to Pittsburgh  ...           0
7            Cincinnati to Buffalo  ...           0
8              Buffalo to New York  ...           0
9           Pittsburgh to New York  ...           0
10             Chicago to New York  ...           2
11  Cost ($1000) for each sequence  ...           3
12                           Hours  ...         179

[13 rows x 9 columns]

In [ ]:
schedule = df.iloc[:-2]  #data for scheduled flights
cost = df.iloc[-2]       #data for cost
hours = df.iloc[-1]      #data for hours

In [ ]:
#if aircrafts are available then 1, if not then 0
schedule = schedule.applymap(lambda x: 1 if x == 1 else x)
schedule = schedule.applymap(lambda x: 1 if x == 2 else x)
schedule = schedule.applymap(lambda x: 1 if x == 3 else x)
schedule = schedule.applymap(lambda x: 1 if x == 4 else x)
schedule = schedule.applymap(lambda x: 1 if x == 5 else x)
schedule = schedule.applymap(lambda x: 1 if x == 6 else x)
schedule = schedule.applymap(lambda x: 1 if x == 7 else x)
schedule = schedule.applymap(lambda x: 1 if x == 8 else x)
schedule = schedule.applymap(lambda x: 1 if x == 9 else x)


schedule

Unnamed: 0  ...  Unnamed: 8
0       Requirement (Flight)  ...           1
1        New York to Buffalo  ...           0
2     New York to Cincinnati  ...           0
3        New York to Chicago  ...           1
4         Buffalo to Chicago  ...           0
5      Chicago to Cincinnati  ...           0
6   Cincinnati to Pittsburgh  ...           0
7      Cincinnati to Buffalo  ...           0
8        Buffalo to New York  ...           0
9     Pittsburgh to New York  ...           0
10       Chicago to New York  ...           1

[11 rows x 9 columns]

In [ ]:
a = schedule.values
a = np.delete(a, [0], axis =1)
a = np.delete(a,[0], axis =0)
print(a) #array for scheduled flights

b = np.ones(len(a))
print(b) #array for atleast one trip

c = cost.values[1:]
print(c) #array for cost

[[1 0 0 1 0 0 1 0]
 [0 1 0 0 1 0 0 0]
 [0 0 1 0 0 1 0 1]
 [1 0 0 1 0 0 0 0]
 [0 0 1 1 0 1 0 0]
 [0 1 0 1 0 1 0 0]
 [0 0 1 0 1 0 0 0]
 [0 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 0]
 [1 0 0 0 0 0 0 1]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 4 4 9 7 8 3 3]


In [ ]:
h = hours.values[1:]
h  #array for hours

array([396, 352, 1022, 847, 687, 531, 236, 179], dtype=object)

In [ ]:
y = cp.Variable(len(c), boolean=True)  #scalaroptimization variable

In [ ]:
obj = cp.Minimize(c @ y) #defining objective

In [ ]:
constraints = [a @ y >= b, h @ y <= 1700]

In [ ]:
prob = cp.Problem(obj, constraints)
prob.solve(solver=cp.GLPK_MI)

20.0

In [ ]:
print(y.value)

[1. 0. 0. 0. 1. 1. 0. 0.]


In [ ]:
z = schedule.values
z= np.delete(z,[0], axis =0)
s = y.value
print(z)

[['New York to Buffalo' 1 0 0 1 0 0 1 0]
 ['New York to Cincinnati' 0 1 0 0 1 0 0 0]
 ['New York to Chicago' 0 0 1 0 0 1 0 1]
 ['Buffalo to Chicago' 1 0 0 1 0 0 0 0]
 ['Chicago to Cincinnati' 0 0 1 1 0 1 0 0]
 ['Cincinnati to Pittsburgh' 0 1 0 1 0 1 0 0]
 ['Cincinnati to Buffalo' 0 0 1 0 1 0 0 0]
 ['Buffalo to New York' 0 0 1 0 1 0 1 0]
 ['Pittsburgh to New York' 0 1 0 1 0 1 0 0]
 ['Chicago to New York' 1 0 0 0 0 0 0 1]]


In [ ]:
for k in range(len(s)):
  if s[k]==1:
    for i in range(len(z)):  
      if z[i][k+1]==1:
        print(z[i][0])    
    print("\n")

New York to Buffalo
Buffalo to Chicago
Chicago to New York


New York to Cincinnati
Cincinnati to Buffalo
Buffalo to New York


New York to Chicago
Chicago to Cincinnati
Cincinnati to Pittsburgh
Pittsburgh to New York




In [ ]:
ti= [750, 935, 960, 965, 1065, 1125, 1135, 1245, 1385, 1395]   # flight start time in minutes
Ti= [130, 125, 175, 150, 132, 160, 175, 130, 160, 170]         # time taken by airplane 2-way in minutes
Ni= [160, 180, 175, 170, 165, 160, 173, 174, 175, 180]         # no. of passengers
oi= [250, 250, 250, 400, 250, 250, 400, 250, 250, 400]         # compensation amount

captain= [1,1,1,1,1,2,2,2,2,2,3,3,3,3,3,4,4,4,4,4,4,4,5,5,5,5,5,5,6,6,6,6,6,7,7,7,7,7,7,7,8,9]
first_officer= [1,4,5,6,8,2,6,7,8,9,3,4,6,8,10,1,2,4,5,7,9,10,3,4,5,7,8,9,1,2,3,6,9,1,2,3,5,7,9,10,8,9]
crew_time_unchanged = [150, 170, 150, 220, 200, 220, 220, 200, 220, 220, 170, 170, 220, 200, 170, 150, 140, 170, 140, 140, 140, 140, 200, 200, 200, 200, 200, 200, 150, 80, 50, 220,50, 150, 80, 80, 140, 80, 80, 80, 200,0]
crew_time = [150, 170, 150, 220, 200, 220, 220, 200, 220, 220, 170, 170, 220, 200, 170, 150, 140, 170, 140, 140, 140, 140, 200, 200, 200, 200, 200, 200, 150, 80, 50, 220,50, 150, 80, 80, 140, 80, 80, 80, 200,0]

In [ ]:
def CREWSCHEDULE(Ti,crew_time,captain,first_officer):
  p = [] #for storing index of the crew
  tme = [] #for storing crew time of the selected crew
  cap = 0
  off = 0
  for i in range(0,3):
      mini = min([k for k in crew_time if k >Ti[i]])
      for j in range(0,len(crew_time)):
          if crew_time[j]== mini and captain[j]!=cap and first_officer[j]!=off:
              p.append(j)
              tme.append(crew_time[j])
              crew_time[j] = -1
              cap = captain[j]
              off = first_officer[j]
              break
  for i in range(0, len(p)-2):
    if captain[p[i]] == captain[p[i+2]]:
        if T[i] <= (ti[i+2]-ti[i]):
            captain[p[i+2]] = 1000000*(captain[p[i]])
    elif first_officer[p[i]] == first_officer[p[i+2]]:
        if T[i] <= (ti[i+2]-ti[i]):
            first_officer[p[i+2]] = 1000000*(first_officer[p[i]])
  for i in range(len(p)):
      print("Airplane for Trip",i+1,"-",":", "first officer: ",first_officer[p[i]],"/" ,"captain: ",captain[p[i]])
  print(" ")
  print('combination no.: ', p)             # numbering starts from 0
  print('combination fly time: ', tme)
  return p
my_p = CREWSCHEDULE(Ti,crew_time,captain,first_officer)   

Airplane for Trip 1 - : first officer:  2 / captain:  4
Airplane for Trip 2 - : first officer:  5 / captain:  7
Airplane for Trip 3 - : first officer:  8 / captain:  1
 
combination no.:  [16, 36, 4]
combination fly time:  [140, 140, 200]


CREW SCHEDULING

In [ ]:
ti= [750, 935, 960, 965, 1065, 1125, 1135, 1245, 1385, 1395]   # flight start time in minutes
Ti= [130, 125, 125, 150, 132, 160, 175, 130, 160, 170]         # time taken by airplane 2-way in minutes
Ni= [160, 180, 175, 170, 165, 160, 173, 174, 175, 180]         # no. of passengers
oi= [250, 250, 250, 400, 250, 250, 400, 250, 250, 400]         # compensation amount

captain= [1,1,1,1,1,2,2,2,2,2,3,3,3,3,3,4,4,4,4,4,4,4,5,5,5,5,5,5,6,6,6,6,6,7,7,7,7,7,7,7,8,9]
first_officer= [1,4,5,6,8,2,6,7,8,9,3,4,6,8,10,1,2,4,5,7,9,10,3,4,5,7,8,9,1,2,3,6,9,1,2,3,5,7,9,10,8,9]
crew_time_unchanged = [150, 170, 150, 220, 200, 220, 220, 200, 220, 220, 170, 170, 220, 200, 170, 150, 140, 170, 140, 140, 140, 140, 200, 200, 200, 200, 200, 200, 150, 80, 50, 220,50, 150, 80, 80, 140, 80, 80, 80, 200,0]
crew_time = [150, 170, 150, 220, 200, 220, 220, 200, 220, 220, 170, 170, 220, 200, 170, 150, 140, 170, 140, 140, 140, 140, 200, 200, 200, 200, 200, 200, 150, 80, 50, 220,50, 150, 80, 80, 140, 80, 80, 80, 200,0]


In [ ]:
p = []  #for storing index of the crew
tme = [] #for storing crew time of the selected crew
pair_time = 0
cap = 0
off = 0
for i in range(0,len(Ti)):
    mini = min([k for k in crew_time if k >Ti[i]])
    for j in range(0,len(crew_time)):
        if crew_time[j]== mini and captain[j]!=cap and first_officer[j]!=off:
            p.append(j)
            tme.append(crew_time[j])
            crew_time[j] = -1
            cap = captain[j]
            off = first_officer[j]
            break

for i in range(10):
    print("Crew assigned to Flight",i+1,":", "first officer: ",first_officer[p[i]],"/" ,"captain: ",captain[p[i]])
for i in tme:
  pair_time += i
    
print('combination no.: ', p)
print('combination fly time: ', tme)
print('minimium crew pairing time: ', pair_time)

Crew assigned to Flight 1 : first officer:  2 / captain:  4
Crew assigned to Flight 2 : first officer:  5 / captain:  7
Crew assigned to Flight 3 : first officer:  7 / captain:  4
Crew assigned to Flight 4 : first officer:  4 / captain:  1
Crew assigned to Flight 5 : first officer:  5 / captain:  4
Crew assigned to Flight 6 : first officer:  3 / captain:  3
Crew assigned to Flight 7 : first officer:  8 / captain:  1
Crew assigned to Flight 8 : first officer:  9 / captain:  4
Crew assigned to Flight 9 : first officer:  4 / captain:  3
Crew assigned to Flight 10 : first officer:  7 / captain:  2
combination no.:  [16, 36, 19, 1, 18, 10, 4, 20, 11, 7]
combination fly time:  [140, 140, 140, 170, 140, 170, 200, 140, 170, 200]
minimium crew pairing time:  1610


In [ ]:
# A value 1000000 represents that first_officer or captain wont return in the time for next flight assigned to him
# So a different (first_officer - Captain) pair needs to be assigned
for i in range(0, len(p)-2):
    if captain[p[i]] == captain[p[i+2]]:
        if tme[i] >= (ti[i+2]-ti[i]):
            captain[p[i+2]] = 1000000*(captain[p[i]])
    elif first_officer[p[i]] == first_officer[p[i+2]]:
        if tme[i] >= (ti[i+2]-ti[i]):
            first_officer[p[i+2]] = 1000000*(first_officer[p[i]])

for i in range(10):
  if captain[p[i]]%1000000 == 0:
    print("Crew assigned to Flight",i+1,":", "first officer: ",first_officer[p[i]],"/" ,"captain: ",int(captain[p[i]]/1000000), "[Still on flight", i-1, ', infeasible assignment]')
  else:
    print("Crew assigned to Flight",i+1,":", "first officer: ",first_officer[p[i]],"/" ,"captain: ",captain[p[i]])
    

Crew assigned to Flight 1 : first officer:  2 / captain:  4
Crew assigned to Flight 2 : first officer:  5 / captain:  7
Crew assigned to Flight 3 : first officer:  7 / captain:  4
Crew assigned to Flight 4 : first officer:  4 / captain:  1
Crew assigned to Flight 5 : first officer:  5 / captain:  4 [Still on flight 3 , infeasible assignment]
Crew assigned to Flight 6 : first officer:  3 / captain:  3
Crew assigned to Flight 7 : first officer:  8 / captain:  1
Crew assigned to Flight 8 : first officer:  9 / captain:  4
Crew assigned to Flight 9 : first officer:  4 / captain:  3
Crew assigned to Flight 10 : first officer:  7 / captain:  2


In [ ]:
print("compensation cost= $",Ni[4]*oi[4])

compensation cost= $ 41250
